project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!/./do4ds-env/"
execute:
  freeze: false
website:
  favicon: /./www/favicon.ico
  site-url: "https://r-leyshon.github.io/do4ds-labs/"
  description: "Site created during workthrough of DevOps for Data Science Labs"
  search: false
  title: "Exploring Palmer Penguins"
format:
  html:
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6658778373981809" crossorigin="anonymous"></script>
    theme: vapor
    css: /www/styles.css
    toc: true
    number-sections: true
