name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
  
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          use-public-rspm: true

      - name: Setup renv and install packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/all/latest
  
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18'
          cache: 'pip'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          activate-environment: conda-env-do4ds-env-py

      - name: Install python deps
        run: |
          pip install jupyter
          pip install -r requirements.txt
  
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.540
  
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  